FinancialTransaction.create(transaction_type: 1,description: 'Débito',kind: 'Entrada',sign: '+')
FinancialTransaction.create(transaction_type: 2,description: 'Boleto',kind: 'Saída',sign: '-')
FinancialTransaction.create(transaction_type: 3,description: 'Financiamento',kind: 'Saída',sign: '-')
FinancialTransaction.create(transaction_type: 4,description: 'Crédito',kind: 'Entrada',sign: '+')
FinancialTransaction.create(transaction_type: 5,description: 'Recebimento Empréstimo',kind: 'Entrada',sign: '+')
FinancialTransaction.create(transaction_type: 6,description: 'Vendas',kind: 'Entrada',sign: '+')
FinancialTransaction.create(transaction_type: 7,description: 'Recebimento TED',kind: 'Entrada',sign: '+')
FinancialTransaction.create(transaction_type: 8,description: 'Recebimento DOC',kind: 'Entrada',sign: '+')
FinancialTransaction.create(transaction_type: 9,description: 'Aluguel',kind: 'Saída',sign: '-')
